server:
  port: 9003
spring:
  application:
    name: spring-cloud-nacos-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST}:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: hello_route
          #格式为：lb://应用注册服务名
          uri: lb://spring-cloud-nacos-producer
          predicates:
            - Method=GET
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
# 日志
logging:
  file: /application/applogs/gateway.log